name: Build
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: rustup toolchain install nightly --profile minimal && rustup component add rust-src --toolchain nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
          workspaces: 'src-tauri'
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install NPM Dependencies
        run: pnpm i
      - name: Update Meta
        id: update_meta
        run: |
          $tag = git describe --tags --abbrev=0 2>$null
          if (-not $tag) { $tag = "0.0.0" }
          $TAG = $tag -replace '^v', ''
          $PKGVER = "r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          $cstTimeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("China Standard Time")
          $utcNow = [System.DateTime]::UtcNow
          $cstTime = [System.TimeZoneInfo]::ConvertTimeFromUtc($utcNow, $cstTimeZone)
          $BUILDMETA = $cstTime.ToString("yyMMddHHmm")
          (Get-Content ./src-tauri/Cargo.toml -Raw) -replace '(?m)^(version = "\d+\.\d+\.\d+)', "version = `"$TAG-$PKGVER+$BUILDMETA" | Set-Content ./src-tauri/Cargo.toml -Encoding utf8
          echo "version=$TAG-$PKGVER+$BUILDMETA" >> $env:GITHUB_OUTPUT
      - name: Build
        run: pnpm build
      - name: Copy Binary
        run: copy src-tauri/target/release/kachina-builder.exe kachina-builder.exe
      - name: Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          path: |
            src-tauri/target/release/*.exe
            src-tauri/target/release/*.pdb
      - name: Sentry upload
        if: startsWith(github.ref, 'refs/tags/')
        continue-on-error: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: yuehaiteam
          SENTRY_PROJECT: kachina-installer
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
        run: |
          $ErrorActionPreference = "Stop"
          $env:SENTRY_LOG_LEVEL = "info"
          echo "Creating Sentry release for version ${{ steps.update_meta.outputs.version }}"
          pnpm exec sentry-cli releases new "${{ steps.update_meta.outputs.version }}"
          echo "Setting release metadata for version ${{ steps.update_meta.outputs.version }}"
          pnpm exec sentry-cli releases set-commits --auto "${{ steps.update_meta.outputs.version }}"
          echo "Uploading debug files for version ${{ steps.update_meta.outputs.version }}"
          pnpm exec sentry-cli debug-files upload ./src-tauri/target/release/kachina_installer.pdb
          echo "Finalizing release for version ${{ steps.update_meta.outputs.version }}"
          pnpm exec sentry-cli releases finalize "${{ steps.update_meta.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kachina-builder.exe
          make_latest: true
